### ISSUE TITLE
Hyperlink to contribute to the project is incorrect.

### ISSUE THREAD

**Issue by raghuramdr** [00krishna-tools/nyuki#1]
Hi, I came across this project on the DataKind Slack channel. I noticed that on the [Contributing](https://nyuki-a-geospatial-toolkit-for-humans.readthedocs.io/en/latest/contributing.html) page of the project, the Report Bugs points has the incorrect URL to report bugs. It points to https://github.com/00krishna/nyuki/issues, instead of https://github.com/00krishna-tools/nyuki/issues.

**Comment by 00krishna** [comment]
@raghuramdr Oh thanks so much for the suggestion. Yeah, we are still trying to resolve some issues with the python GDAL package and all, since we ran into some issues running the code on Windows for large files. So hopefully once we get those resolved we can really start to open up to a wider community.

**Comment by 00krishna** [comment]
Approved pull request https://github.com/00krishna-tools/nyuki/pull/2

**Comment by raghuramdr** [comment]
Oh, okay. The link to the repo was put out on Slack, so I thought it was ready. Thanks for the information. :)
